const bancoPreguntas = [
    // --- CMMI (15 preguntas) ---
    { tema: "CMMI", q: "¿Qué significan las siglas CMMI?", options: ["Capability Maturity Model Integration", "Control Management Model Integration", "Computerized Maturity Model Integration"], correct: 0 },
    { tema: "CMMI", q: "¿Cómo se caracteriza el Nivel 1 (Inicial) de madurez?", options: ["Proceso medido y controlado", "Proceso proactivo y organizado", "Proceso impredecible, mal controlado y reactivo"], correct: 2 },
    { tema: "CMMI", q: "En el Nivel 2 (Gestionado), ¿a qué nivel se caracterizan los procesos?", options: ["A nivel organización", "A nivel individual", "A nivel de proyectos"], correct: 2 },
    { tema: "CMMI", q: "¿Cuál es una diferencia clave entre el Nivel 2 y el Nivel 3?", options: ["El ámbito de los estándares y descripción de procesos", "El uso de herramientas estadísticas", "La falta de presupuesto total"], correct: 0 },
    { tema: "CMMI", q: "¿Cómo se describe el proceso en el Nivel 3 (Definido)?", options: ["Caótico y ad hoc", "Cuantitativamente predecible", "Cualitativamente predecible"], correct: 2 },
    { tema: "CMMI", q: "¿Qué caracteriza al Nivel 4 (Gestionado Cuantitativamente)?", options: ["Procesos informales y reactivos", "Uso de técnicas estadísticas para controlar sub-procesos", "Foco exclusivo en la mejora continua manual"], correct: 1 },
    { tema: "CMMI", q: "¿Cuál es el foco principal del Nivel 5 (Optimización)?", options: ["Mejora continua del rendimiento de los procesos", "Establecer la gestión básica de proyectos", "Definir requisitos por primera vez"], correct: 0 },
    { tema: "CMMI", q: "En el Nivel 1, ¿de qué depende principalmente el éxito de la organización?", options: ["De procesos probados", "De herramientas automatizadas", "De la competencia y disposición de las personas"], correct: 2 },
    { tema: "CMMI", q: "¿Qué nivel tiene como resultado 'Máxima calidad y menor riesgo'?", options: ["Nivel 3", "Nivel 5", "Nivel 4"], correct: 1 },
    { tema: "CMMI", q: "¿En qué nivel se encuentra el Área Clave de Proceso 'Gestión de Riesgos'?", options: ["Nivel 3", "Nivel 2", "Nivel 4"], correct: 0 },
    { tema: "CMMI", q: "¿Qué tipo de variación de procesos se encargan en el Nivel 5?", options: ["Causas especiales", "Causas externas", "Causas comunes"], correct: 2 },
    { tema: "CMMI", q: "¿Qué significa ser 'Proactivo' según la definición del Nivel 3?", options: ["Esperar a que ocurra una crisis para actuar", "Actuar rápidamente para evitar complicaciones futuras", "Seguir procedimientos solo bajo supervisión"], correct: 1 },
    { tema: "CMMI", q: "¿Cuál es el resultado de calidad y riesgo típico en el Nivel 2?", options: ["Calidad media / Riesgo medio", "Alta calidad / Riesgo bajo", "Baja calidad / Alto Riesgo"], correct: 2 },
    { tema: "CMMI", q: "¿Qué técnica permite conocer una tendencia de opinión o preferencia?", options: ["Técnicas Cuantitativas", "Técnicas Cualitativas", "Análisis Causal"], correct: 0 },
    { tema: "CMMI", q: "En el Nivel 4, ¿cómo se administran la calidad y el rendimiento?", options: ["Mediante observación cualitativa", "A través de términos estadísticos", "Según la velocidad de entrega de servicios"], correct: 1 },

    // --- MOPROSOFT (20 preguntas) ---
    { tema: "Moprosoft", q: "¿En qué país nació Moprosoft?", options: ["España", "México", "Chile"], correct: 1 },
    { tema: "Moprosoft", q: "¿A qué norma ISO equivale?", options: ["ISO 9001", "ISO 15504", "ISO 27001"], correct: 1 },
    { tema: "Moprosoft", q: "¿A qué empresas se enfoca?", options: ["Grandes", "MiPyMEs", "Gobierno"], correct: 1 },
    { tema: "Moprosoft", q: "¿Cuál es un proceso de Alta Dirección?", options: ["Gestión de Negocio", "Gestión de Proyectos", "Desarrollo"], correct: 0 },
    { tema: "Moprosoft", q: "¿Cuál es un proceso de Gerencia?", options: ["Gestión de Recursos", "Gestión de Negocio", "Mantenimiento"], correct: 0 },
    { tema: "Moprosoft", q: "¿Cuál es un proceso de Operación?", options: ["Desarrollo de Software", "Gestión de Recursos", "Gestión de Negocio"], correct: 0 },
    { tema: "Moprosoft", q: "¿Cuántas categorías de procesos tiene?", options: ["2", "3", "4"], correct: 1 },
    { tema: "Moprosoft", q: "¿Qué busca la Gestión de Negocio?", options: ["Estrategia y clientes", "Contratar gente", "Hacer código"], correct: 0 },
    { tema: "Moprosoft", q: "¿Qué incluye la Gestión de Recursos?", options: ["RRHH e Infraestructura", "Solo dinero", "Solo computadoras"], correct: 0 },
    { tema: "Moprosoft", q: "¿Qué es el Patrón de Procesos?", options: ["El jefe", "Estructura para describir procesos", "Un diagrama de flujo"], correct: 1 },
    { tema: "Moprosoft", q: "¿Cuántos niveles de capacidad tiene?", options: ["Del 1 al 5", "Del 0 al 5", "Del 1 al 3"], correct: 1 },
    { tema: "Moprosoft", q: "¿Qué proceso busca la mejora organizacional?", options: ["Administración de Procesos", "Gestión de Proyectos", "Mantenimiento"], correct: 0 },
    { tema: "Moprosoft", q: "¿Qué evalúa Moprosoft?", options: ["Hardware", "Procesos de software", "Ventas"], correct: 1 },
    { tema: "Moprosoft", q: "¿Quién promovió Moprosoft?", options: ["SE", "SEP", "SRE"], correct: 0 },
    { tema: "Moprosoft", q: "¿Qué es la base de conocimiento?", options: ["Biblioteca", "Repositorio de activos de procesos", "Un disco duro"], correct: 1 },
    { tema: "Moprosoft", q: "¿En qué categoría está Gestión de Proyectos?", options: ["Alta Dirección", "Gerencia", "Operación"], correct: 1 },
    { tema: "Moprosoft", q: "¿Qué busca el nivel 0?", options: ["Incompleto", "Realizado", "Establecido"], correct: 0 },
    { tema: "Moprosoft", q: "¿Qué nivel es 'Optimizado'?", options: ["Nivel 3", "Nivel 4", "Nivel 5"], correct: 2 },
    { tema: "Moprosoft", q: "¿Qué rol lidera la Alta Dirección?", options: ["Director General", "Project Manager", "Desarrollador"], correct: 0 },
    { tema: "Moprosoft", q: "¿Moprosoft es compatible con CMMI?", options: ["Sí", "No", "Solo nivel 1"], correct: 0 },

    // --- TSP (20 preguntas) ---
    { tema: "TSP", q: "¿Qué significa TSP?", options: ["Team Software Process", "Total Software Process", "Task System Process"], correct: 0 },
    { tema: "TSP", q: "¿Quién creó TSP?", options: ["Watts Humphrey", "Bill Gates", "Alan Turing"], correct: 0 },
    { tema: "TSP", q: "¿Cuál es el enfoque de TSP?", options: ["Trabajo en equipo", "Trabajo individual", "Solo gerencia"], correct: 0 },
    { tema: "TSP", q: "¿Qué es el Launch?", options: ["Lanzamiento de cohetes", "Reunión de planeación del equipo", "Cena de fin de proyecto"], correct: 1 },
    { tema: "TSP", q: "¿Qué es un equipo autodirigido?", options: ["Equipo sin reglas", "Equipo que planea y decide unido", "Equipo con robot"], correct: 1 },
    { tema: "TSP", q: "¿Cuántas fases tiene el Launch?", options: ["4", "9", "3"], correct: 1 },
    { tema: "TSP", q: "¿Qué rol gestiona el tiempo?", options: ["Líder de Planeación", "Líder de Calidad", "Líder de Soporte"], correct: 0 },
    { tema: "TSP", q: "¿Qué rol monitorea los defectos?", options: ["Líder de Calidad", "Desarrollador", "Líder de Soporte"], correct: 0 },
    { tema: "TSP", q: "¿Qué hace el Líder de Soporte?", options: ["Configuración y herramientas", "Hacer café", "Atención al cliente"], correct: 0 },
    { tema: "TSP", q: "¿Qué hace el Líder de Proyecto?", options: ["Dirige y motiva al equipo", "Escribe todo el código", "No hace nada"], correct: 0 },
    { tema: "TSP", q: "¿Cada cuánto hay reuniones de estado?", options: ["Cada mes", "Cada semana", "Cada año"], correct: 1 },
    { tema: "TSP", q: "¿Qué es un Ciclo en TSP?", options: ["Iteración de desarrollo", "Giro de rueda", "Vida del programador"], correct: 0 },
    { tema: "TSP", q: "¿Qué busca el Postmortem?", options: ["Analizar datos finales", "Culpar a alguien", "Ver una película"], correct: 0 },
    { tema: "TSP", q: "¿Cuál es la meta principal de TSP?", options: ["Calidad y cumplimiento", "Rapidez extrema", "Bajo costo"], correct: 0 },
    { tema: "TSP", q: "¿TSP requiere PSP?", options: ["Sí", "No", "Opcional"], correct: 0 },
    { tema: "TSP", q: "¿Qué es la 'Estrategia' en TSP?", options: ["Cómo se abordará el diseño", "Un juego de mesa", "Engañar al cliente"], correct: 0 },
    { tema: "TSP", q: "¿Qué es el Plan de Calidad?", options: ["Metas de defectos", "Solo probar al final", "Documento de 500 hojas"], correct: 0 },
    { tema: "TSP", q: "¿Qué es el registro de riesgos?", options: ["Identificar posibles fallos", "Seguro médico", "Lista de precios"], correct: 0 },
    { tema: "TSP", q: "¿Quién toma las decisiones técnicas?", options: ["El equipo", "Solo el jefe", "El cliente"], correct: 0 },
    { tema: "TSP", q: "¿Qué mide el TSP?", options: ["Productividad y calidad grupal", "Solo líneas de código", "Horas de sueño"], correct: 0 },

    // --- PSP (Preguntas base para que las piezas azules no estén vacías) ---
    { tema: "PSP", q: "¿Cuál es el objetivo de PSP?", options: ["Mejorar disciplina individual", "Gestión de hardware", "Ventas"], correct: 0 },
    { tema: "PSP", q: "¿Qué herramienta usa PSP para estimar?", options: ["PROBE", "Excel básico", "Cronómetro"], correct: 0 },
    { tema: "PSP", q: "¿Qué registra el log de tiempos?", options: ["Interrupciones y tareas", "Solo errores", "Hora de comida"], correct: 0 }
];